version: '3'

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_aic_static_php
    build: 
      context: ./aic/php
      args:
          - PHP_VERSION=${PHP_VERSION}
    image: aic/php${PHP_VERSION}
    volumes:
      - './aic/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './dest:/var/www/html'
      - './src/:/var/www/src'
    environment:
      FILE_EXTENSION: ${FILE_EXTENSION}

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_aic_static_nginx
    build:
        context: ./aic/nginx
        args:
            - NGINX_VERSION=${NGINX_VERSION}
    image: aic/nginx${NGINX_VERSION}
    volumes:
      - './aic/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './dest:/var/www/html'
    ports:
      - "8000:80"
    restart: always
    depends_on: ["php"]
